[package]
name = "nms-video-launcher"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "nms-video-launcher"
path = "src/main.rs"

[dependencies]
windows = { workspace = true }
itk-ipc = { path = "../../../core/itk-ipc" }
itk-protocol = { path = "../../../core/itk-protocol" }

[lints]
workspace = true
